SCR_MissionHeader : "{3D094352621EA88C}Missions/CRF_BaseMissionConfig.conf" {
 World "{841C3D762329C1C4}Worlds/COALobby/Ruha/CCO21.ent"
 m_sName "CRF CCO128 Northern Flight"
 m_sDescription "CCO #21"
 m_sGameMode "CCO"
 m_sTerrainName "Ruha"
}