SCR_MissionHeader {
 World "{BE6C7C0C9774C450}Worlds/COALobby/Kolguyev/SAL_COOP_SilentThunder.ent"
 m_sName "CRF COOP48 Silent Thunder"
 m_sAuthor "Salami"
 m_sDescription "CCO Systems Test"
 m_sIcon "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sLoadingScreen "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sPreviewImage "{B7385DA4504BD4D5}CRF Images/crflogo.edds"
 m_sGameMode "COOP"
 m_iPlayerCount 128
 m_iStartingHours 12
 m_iMapMarkerLimitPerPlayer 120
}